const http=require('http');const fs=require('fs');const{spawn}=require('child_process');const httpProxy=require('http-proxy');
const PORT=Number(process.env.PORT||3000),XRAY_PORT=Number(process.env.XRAY_PORT||10000),UUID=process.env.UUID,WS_PATH=process.env.WS_PATH||'/vless',DOMAIN=process.env.DOMAIN||process.env.RAILWAY_PUBLIC_DOMAIN||'',API_KEY=process.env.API_KEY||'';
if(!UUID){console.error('UUID environment variable is required.');process.exit(1)}
const config=fs.readFileSync('/app/config/config.template.json','utf8').replaceAll('${UUID}',UUID).replaceAll('${WS_PATH}',WS_PATH).replaceAll('10000',String(XRAY_PORT));JSON.parse(config);fs.writeFileSync('/app/config/runtime.json',config);
const xray=spawn(process.env.XRAY_BIN||'/opt/xray/xray',['run','-c',process.env.XRAY_CONFIG||'/app/config/runtime.json'],{stdio:['ignore','pipe','pipe']});xray.stdout.on('data',d=>process.stdout.write(`[xray] ${d}`));xray.stderr.on('data',d=>process.stderr.write(`[xray] ${d}`));xray.on('exit',c=>process.exit(c||1));
const proxy=httpProxy.createProxyServer({target:`http://127.0.0.1:${XRAY_PORT}`,ws:true,xfwd:true});proxy.on('error',(e,req,res)=>{console.error(e.message);if(res&&!res.headersSent){res.writeHead(502,{'content-type':'application/json'});res.end(JSON.stringify({error:'Xray proxy unavailable'}))}});
const auth=req=>!API_KEY||req.headers['x-api-key']===API_KEY;
function link(){if(!DOMAIN)return null;const p=new URLSearchParams({encryption:'none',security:'tls',type:'ws',host:DOMAIN,sni:DOMAIN,path:WS_PATH});return `vless://${UUID}@${DOMAIN}:443?${p}#Railway-VLESS`}
const server=http.createServer((req,res)=>{if(req.url==='/'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,protocol:'VLESS',transport:'WebSocket',path:WS_PATH,domain:DOMAIN||null}))}if(req.url==='/health'){res.writeHead(200);return res.end('ok')}if(req.url==='/api/config'){if(!auth(req)){res.writeHead(401);return res.end(JSON.stringify({error:'unauthorized'}))}res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({protocol:'VLESS',transport:'WebSocket',domain:DOMAIN||null,path:WS_PATH,link:link()},null,2))}if(req.url==='/api/uuid'){if(!auth(req)){res.writeHead(401);return res.end(JSON.stringify({error:'unauthorized'}))}res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({uuid:UUID}))}if(req.url===WS_PATH)return proxy.web(req,res);res.writeHead(404);res.end(JSON.stringify({error:'not_found'}))});
server.on('upgrade',(req,socket,head)=>{if(new URL(req.url,'http://localhost').pathname!==WS_PATH)return socket.destroy();proxy.ws(req,socket,head)});server.listen(PORT,'0.0.0.0',()=>console.log(`Gateway listening on ${PORT}`));
